<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
